export const ui = {
  colors: {
    bg: '#fff6e9',
    bgMuted: '#f8e7cc',
    card: '#fffcf7',
    cardAlt: '#fff4e2',
    surfaceWarm: '#fff8ef',
    surfaceSoft: '#fffdf9',
    surfaceSun: '#fff3df',
    surfaceAccent: '#f2f7fa',
    text: '#3a2a1c',
    textSecondary: '#6e533d',
    textTertiary: '#9a7d60',
    primary: '#d57a2f',
    primaryStrong: '#a95a22',
    primarySoft: '#fde3c2',
    primaryBorder: '#e7bd8f',
    accent: '#5e97a7',
    accentSoft: '#e8f2f5',
    accentBorder: '#c5dae2',
    border: '#e8d3b6',
    borderStrong: '#debe95',
    danger: '#cc5e4b',
    dangerSoft: '#fbe6e2',
    dangerBorder: '#e7beb5',
    success: '#5e9066',
    successSoft: '#e9f3ea',
    info: '#5e8eaa',
    infoSoft: '#e7f0f6',
    tabBg: '#fff9f1',
    shadow: '#2d2217',
  },
  radius: {
    sm: 12,
    md: 16,
    lg: 22,
    xl: 28,
    pill: 999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
  },
};

export const gradients = {
  page: ['#fff2de', '#fff9f0', '#f6fbfd'] as const,
  hero: ['#ffe8c8', '#fff4e2'] as const,
};
